# Generated by Django 2.2.4 on 2019-09-01 03:58

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Digite seu nome', max_length=50, verbose_name='Nome')),
                ('name2', models.CharField(help_text='Digite seu sobrenome', max_length=50, verbose_name='Sobrenome')),
                ('email', models.EmailField(help_text='Digite seu e-mail', max_length=254, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[account.validators.validate_CPF])),
                ('country', models.CharField(choices=[('0', ' '), ('1', 'Brasil')], default=0, max_length=50)),
                ('region', models.CharField(choices=[('0', ' '), ('1', 'Sao Paulo'), ('2', 'Rio de Janeiro')], default=0, max_length=50)),
                ('adress', models.CharField(help_text='Digite seu endereço', max_length=50, verbose_name='Endereço')),
                ('sex', models.CharField(choices=[('0', ' '), ('1', 'Homem'), ('2', 'Mulher')], help_text='Selecione seu sexo', max_length=50, verbose_name='Sexo')),
                ('created_in', models.DateTimeField()),
            ],
        ),
    ]
