# Generated by Django 2.2.4 on 2019-09-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
