# Generated by Django 2.2.4 on 2019-09-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190901_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='created_in',
            field=models.DateTimeField(),
        ),
    ]
