# Generated by Django 2.2.4 on 2019-09-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190918_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='adress',
            field=models.CharField(max_length=50, verbose_name='Endereço'),
        ),
    ]
