# Generated by Django 2.2.4 on 2019-09-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190918_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(choices=[('0', ' '), ('1', 'São Bernardo'), ('2', 'Diadema'), ('3', 'Santo André'), ('4', 'São Caetano do Sul')], default=0, max_length=50, verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='person',
            name='region',
            field=models.CharField(choices=[('0', ' '), ('1', 'São Bernardo'), ('2', 'Diadema'), ('3', 'Santo André'), ('4', 'São Caetano do Sul')], default=0, max_length=50, verbose_name='Região'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('0', ''), ('1', 'Homem'), ('2', 'Mulher')], help_text='Selecione seu sexo', max_length=50, verbose_name='Sexo'),
        ),
    ]
