# Generated by Django 2.2.4 on 2019-09-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190918_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=False, max_length=20, verbose_name='Ativo'),
        ),
    ]
