# Generated by Django 2.2.4 on 2019-10-02 01:34

import account.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_person_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='adress',
            field=models.CharField(help_text='Endereço do Usuário', max_length=50, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(max_length=12, unique=True, validators=[account.validators.validate_CPF], verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(help_text='Nome do Usuário', max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name2',
            field=models.CharField(help_text='Sobrenome do Usuário', max_length=50, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('0', ''), ('1', 'Homem'), ('2', 'Mulher')], max_length=50, verbose_name='Sexo'),
        ),
    ]
