# Generated by Django 2.2.4 on 2019-10-08 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20191002_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_professional',
            field=models.BooleanField(default=False, help_text='Se o usuário for Empresa/Profissional Ativado', max_length=12, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.FileField(default=None, upload_to='./account/picture/'),
        ),
        migrations.CreateModel(
            name='Dots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dots', models.BigIntegerField(editable=False, verbose_name='Dots')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Person', verbose_name='Person')),
            ],
        ),
    ]
