# Generated by Django 2.2.4 on 2019-10-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20191008_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
