# Generated by Django 2.2.4 on 2019-10-08 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20191008_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='picture',
        ),
    ]
