# Generated by Django 2.2.4 on 2019-10-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_remove_person_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.FileField(default='', upload_to='./account/picture/'),
        ),
    ]
