# Generated by Django 2.2.6 on 2019-10-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_person_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(upload_to='./account/picture/'),
        ),
    ]
