# Generated by Django 2.2.6 on 2019-10-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20191008_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
