# Generated by Django 2.2.4 on 2019-09-01 03:58

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Digite o nome', max_length=50, verbose_name='Empresa')),
                ('country', models.IntegerField(choices=[('0', ' '), ('1', 'Brasil')], default=0)),
                ('region', models.CharField(choices=[('0', ' '), ('1', 'Sao Paulo'), ('2', 'Rio de Janeiro')], default=0, max_length=50)),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[account.validators.validate_CNPJ])),
                ('adress', models.CharField(help_text='Digite seu endereço', max_length=50, verbose_name='Endereço')),
            ],
        ),
    ]
